"""Add calls_rel table

Revision ID: f97d38cf9ce2
Revises: 
Create Date: 2023-11-21 20:21:35.480968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f97d38cf9ce2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calls_rel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('function_qualified_name', sa.String(), nullable=True),
    sa.Column('called_function_qualified_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calls_rel', schema='public')
    # ### end Alembic commands ###
