"""Add is_linked field

Revision ID: bab1e6a5d721
Revises: f97d38cf9ce2
Create Date: 2023-11-21 23:26:35.240827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bab1e6a5d721'
down_revision: Union[str, None] = 'f97d38cf9ce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls_rel', sa.Column('is_linked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calls_rel', 'is_linked')
    # ### end Alembic commands ###
