"""Add classes and functions table

Revision ID: 30e4aabcf768
Revises: a44606deda3a
Create Date: 2024-01-11 18:30:08.283232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30e4aabcf768'
down_revision: Union[str, None] = 'a44606deda3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_qualified_name', sa.String(), nullable=True),
    sa.Column('is_created', sa.Boolean(), nullable=False),
    sa.Column('attributes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('functions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('function_qualified_name', sa.String(), nullable=True),
    sa.Column('is_created', sa.Boolean(), nullable=False),
    sa.Column('attributes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.alter_column('calls_rel', 'is_linked',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('inherits_rel', 'is_linked',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inherits_rel', 'is_linked',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('calls_rel', 'is_linked',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_table('functions', schema='public')
    op.drop_table('classes', schema='public')
    # ### end Alembic commands ###
