"""Add inherits table

Revision ID: a44606deda3a
Revises: bab1e6a5d721
Create Date: 2024-01-11 13:49:40.858251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a44606deda3a'
down_revision: Union[str, None] = 'bab1e6a5d721'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inherits_rel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_qualified_name', sa.String(), nullable=True),
    sa.Column('inherited_class_qualified_name', sa.String(), nullable=True),
    sa.Column('is_linked', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inherits_rel', schema='public')
    # ### end Alembic commands ###
