"""Update column names

Revision ID: faf76753d548
Revises: 30e4aabcf768
Create Date: 2024-01-11 18:46:21.211395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faf76753d548'
down_revision: Union[str, None] = '30e4aabcf768'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('name', sa.String(), nullable=True))
    op.add_column('classes', sa.Column('qualified_name', sa.String(), nullable=True))
    op.drop_column('classes', 'class_qualified_name')
    op.add_column('functions', sa.Column('name', sa.String(), nullable=True))
    op.add_column('functions', sa.Column('qualified_name', sa.String(), nullable=True))
    op.drop_column('functions', 'function_qualified_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('functions', sa.Column('function_qualified_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('functions', 'qualified_name')
    op.drop_column('functions', 'name')
    op.add_column('classes', sa.Column('class_qualified_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('classes', 'qualified_name')
    op.drop_column('classes', 'name')
    # ### end Alembic commands ###
